#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

echo "Post-push processing image: ${IMAGE_NAME}"

# Tag and push image for each additional tag
for tag in \
  $(git log -1 --pretty=%h || echo "") \
  $(git branch | grep \* | cut -d ' ' -f2 || echo "")\
  $(git tag -l --points-at HEAD | sed 's/^v//' || echo ""); do
    echo "Additional tag: ${tag}"
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag} || echo "Additional tag: ${tag} not pushed"
done