#!/bin/bash

set -e

# Parse image name
tagStart=$(expr index "${IMAGE_NAME}" :)
#repoName=${IMAGE_NAME:0:tagStart-1}

echo "Post-push processing image: ${IMAGE_NAME}. Tag: ${IMAGE_NAME:tagStart}. Docker tag:  ${DOCKER_TAG}." ## For some reason ${CACHE_TAG} is not available
echo "Current commit=${SOURCE_COMMIT}"
echo "Current branch=${SOURCE_BRANCH}"

# Additional tags,
# IF triggered by tag
if [[ "${DOCKER_TAG}" =~ ^v?([0-9.]+.*) ]]; then
  CTAG="${DOCKER_TAG}_${SOURCE_COMMIT}"
  echo "Additional compound tag: ${CTAG}"
  docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${CTAG}
  docker push ${DOCKER_REPO}:${CTAG}
else
  # for tag in ${SOURCE_COMMIT} ${SOURCE_BRANCH} $(git tag -l --points-at HEAD | sed 's/^v//' || echo ""); do
  for tag in ${SOURCE_COMMIT} ${SOURCE_BRANCH}; do
    echo "Additional tag: ${tag}"
    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${tag}
    docker push ${DOCKER_REPO}:${tag} #|| echo "Additional tag: ${tag} not pushed" #this is designed to ignore post push if build is from version tag
  done
fi